version: '3'

services:
  drawbridge:
    build: .
    image: jakewright/drawbridge
    volumes:
      - ./config.yaml:/config/config.yaml
      - .:/go/src/drawbridge
      - /go/pkg
    ports:
      - 5005:80
